name: Build for Intel Macs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Cache Deps
      uses: actions/cache@v4
      with:
        key: x86_64-cargo-deps-${{ hashFiles('Cargo.lock') }}
        path: |
          target
          ~/.cargo
        restore-keys: |
          x86_64-cargo-deps
    - name: Build Testing
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: ./build_app.sh App
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: PrefSuite-x86_64
        path: App
