name: Build all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_matrix:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-13, macos-latest]
        include:
          - os: macos-13
            arch: x86_64
          - os: macos-latest
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Cache Deps
      id: cache-deps
      uses: actions/cache@v4
      with:
        key: ${{ matrix.arch }}-cargo-deps-${{ hashFiles('Cargo.lock') }}
        path: |
          ./target
          ~/.cargo
        restore-keys: |
          ${{ matrix.arch }}-cargo-deps-

    - name: Build Release
      run: ./build_app.sh App
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: PrefSuite-${{ matrix.arch }}
        path: App

    - if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      name: Optimize cache
      continue-on-error: true
      run: |
        cargo install cargo-cache --no-default-features --features ci-autoclean cargo-cache
        cargo-cache
